### ISSUE TITLE
Batch Get Favorited

### ISSUE THREAD

**Issue by builtbylane** [builtbylane/donda-mood-board#36]
Client sends a user id and an array of ids, and API returns an array of yes/no for whether an item is favorited or not

**Comment by roomnoise** [comment]
Since we're now paginating, instead of sending an array and doing a call I say we do a .map on the item results and run each through a FavoriteItem call.  Indexed correctly, this will only add a few milliseconds to the load and will keep the favorited flags in sync.

Also to do this we'll add a dynamic 'is_favorited' flag to the Items schema.

**Comment by builtbylane** [comment]
That works!
